### ISSUE TITLE
NoPackagesFoundError: Package missing in current Win64 channels:                        - freetype 2.5.5 1

### ISSUE THREAD

**Issue by Ved-Piyush** [zooniverse/Data-digging#24]
I am trying to install this Python Environment using the yml file. However I run into the following error :

    NoPackagesFoundError: Package missing in current Win64 channels: 
                      - freetype 2.5.5 1

I am using the following code to install the environment using Anaconda 2 (after putting the .yml file in the current directory for Python.)

    conda env create -f basic_project_stats.yml

I was not sure what the last line in the yml file which is 'prefix' is doing, but I changed as following to the directory where the python environments reside in my computer . 
    
     prefix: /Users/Public/Anaconda2/envs/python279_volcrowe

I also tried installing a win 64 channel as suggested in a stackoverflow post  using the following code( <https://stackoverflow.com/questions/38739694/install-python-package-package-missing-in-current-win-64-channels?rq=1> 

    conda config --add channels bioninja

I am able to add the bioninja thing but after it when I run the following command: 
    conda env create -f environment.yml

It gives me the same Win64 channel error as earlier. 

Can anyone please help me solve this issue ?

**Comment by vrooje** [comment]
I think I probably should have cleaned up the file before committing it, as the environment I used had a ton of packages that I use for other things but that I haven't (yet) used here. Try deleting the lines that have a problem as a first step. The repo definitely uses pandas and numpy and dateutil, but most other things can probably go (or will automatically be added if needed because of dependencies).

**Comment by vrooje** [comment]
I've simplified the yml file to include only the necessary packages - if that doesn't fix it please reopen and let me know. Thanks :)
